import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../../../../providers/task_provider.dart';
import '../../../../providers/auth_provider.dart';
import '../../../../providers/user_event_provider.dart';
import '../../../../models/task_model.dart';
import '../../../../services/notification_service.dart';

class TasksTab extends StatefulWidget {
  final String eventId;
  const TasksTab({super.key, required this.eventId});

  @override
  State<TasksTab> createState() => _TasksTabState();
}

class _TasksTabState extends State<TasksTab> {
  bool _hasAutoGenerated = false;

  @override
  void initState() {
    super.initState();
    // Use addPostFrameCallback to ensure context is available
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _initializeTasks();
    });
  }

  Future<void> _initializeTasks() async {
    final taskProvider = Provider.of<TaskProvider>(context, listen: false);

    // 1. Start listening to the Firebase stream
    taskProvider.listenToTasks(widget.eventId);

    // 2. Wait for the first set of data to arrive
    await Future.delayed(const Duration(milliseconds: 1000));

    if (!mounted) return;

    // 3. Auto-Generate if the list is still empty
    if (taskProvider.tasks.isEmpty && !_hasAutoGenerated) {
      _hasAutoGenerated = true;
      await _autoGenerateTasksFromCart();
    }
  }

  // 🤖 AUTO GENERATE TASKS BASED ON SERVICES
  Future<void> _autoGenerateTasksFromCart() async {
    final eventProv = Provider.of<UserEventProvider>(context, listen: false);
    final taskProv = Provider.of<TaskProvider>(context, listen: false);
    final auth = Provider.of<AuthProvider>(context, listen: false);

    final event = eventProv.selectedEvent;
    if (event == null) return;

    final userName = auth.user?.name ?? 'User';
    final eventName = event.eventName;

    // Deadline: 3 days before event or tomorrow if that's in the past
    DateTime defaultDeadline = event.eventDate.subtract(const Duration(days: 3));
    if (defaultDeadline.isBefore(DateTime.now())) {
      defaultDeadline = DateTime.now().add(const Duration(days: 1));
    }

    // Basic common tasks
    List<String> autoTaskNames = ["Send Event Invitations", "Confirm Guest List"];

    // Contextual tasks based on what they put in their cart
    for (var item in event.selectedItems) {
      String sName = item.sectionName.toLowerCase();
      if (sName.contains('food')) autoTaskNames.add("Finalize Food Menu");
      if (sName.contains('decor')) autoTaskNames.add("Approve Decor Theme");
      if (sName.contains('photo')) autoTaskNames.add("Discuss Shot List");
      if (sName.contains('music')) autoTaskNames.add("Share Playlist with DJ");
    }

    autoTaskNames = autoTaskNames.toSet().toList(); // Remove duplicates

    for (String name in autoTaskNames) {
      final task = await taskProv.addTask(
        eventId: widget.eventId,
        eventName: eventName,
        userName: userName,
        taskName: name,
        deadline: defaultDeadline,
      );

      // Schedule Push Notifications
      if (task != null) {
        await NotificationService().scheduleTaskReminders(
          task.id,
          task.taskName,
          task.deadline,
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    const Color midnightBlue = Color(0xFF1A237E);

    return Scaffold(
      backgroundColor: Colors.grey.shade50,
      body: Consumer<TaskProvider>(
        builder: (context, provider, child) {
          if (provider.isLoading && provider.tasks.isEmpty) {
            return const Center(child: CircularProgressIndicator());
          }

          return CustomScrollView(
            slivers: [
              SliverToBoxAdapter(child: _buildProgressCard(provider.progress, midnightBlue)),

              if (provider.tasks.isEmpty)
                const SliverFillRemaining(child: Center(child: Text("No tasks yet.")))
              else
                SliverPadding(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  sliver: SliverList(
                    delegate: SliverChildBuilderDelegate(
                          (context, index) => _buildTaskTile(provider.tasks[index], provider, midnightBlue),
                      childCount: provider.tasks.length,
                    ),
                  ),
                ),
              const SliverToBoxAdapter(child: SizedBox(height: 100)),
            ],
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: midnightBlue,
        child: const Icon(Icons.add, color: Colors.white),
        onPressed: () => _showAddTaskSheet(context),
      ),
    );
  }

  // 🎨 DULLED TASK TILE
  Widget _buildTaskTile(EventTask task, TaskProvider provider, Color themeColor) {
    final bool isCompleted = task.isCompleted;
    final bool isOverdue = !isCompleted && task.deadline.isBefore(DateTime.now());

    // 🌈 VISUAL DULLING LOGIC
    // Completed tasks are highly transparent (0.5)
    // Overdue tasks are tinted red
    return AnimatedOpacity(
      duration: const Duration(milliseconds: 300),
      opacity: isCompleted ? 0.5 : 1.0, // <--- THE "DULL" EFFECT
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(
              color: isOverdue ? Colors.red.withOpacity(0.3) : Colors.transparent,
              width: 1.5
          ),
          boxShadow: [
            BoxShadow(
                color: Colors.black.withOpacity(isCompleted ? 0.01 : 0.03),
                blurRadius: 5
            )
          ],
        ),
        child: ListTile(
          onTap: () {
            provider.toggleTask(widget.eventId, task);
            if (!isCompleted) {
              // Note: You might want to cancel specific reminders if you have IDs
              // NotificationService().cancelNotification(task.id.hashCode); 
            }
          },
          leading: Icon(
            isCompleted ? Icons.check_circle : Icons.circle_outlined,
            color: isCompleted ? Colors.green : (isOverdue ? Colors.red : Colors.grey),
          ),
          title: Text(
            task.taskName,
            style: TextStyle(
              fontWeight: FontWeight.w600,
              decoration: isCompleted ? TextDecoration.lineThrough : null,
              color: isCompleted ? Colors.grey : (isOverdue ? Colors.red.shade900 : Colors.black87),
            ),
          ),
          subtitle: Text(
            "${isOverdue ? 'Overdue: ' : 'Due: '}${DateFormat('dd MMM, hh:mm a').format(task.deadline)}",
            style: TextStyle(
              fontSize: 12,
              color: isOverdue ? Colors.red : Colors.grey.shade600,
              fontWeight: isOverdue ? FontWeight.bold : FontWeight.normal,
            ),
          ),
          trailing: isCompleted
              ? null
              : IconButton(
            icon: const Icon(Icons.delete_outline, color: Colors.grey, size: 20),
            onPressed: () => provider.deleteTask(widget.eventId, task.id),
          ),
        ),
      ),
    );
  }

  Widget _buildProgressCard(double progress, Color themeColor) {
    return Container(
      margin: const EdgeInsets.all(20),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: themeColor,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text("Planning Progress", style: TextStyle(color: Colors.white70, fontSize: 14)),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: LinearProgressIndicator(
                  value: progress,
                  backgroundColor: Colors.white24,
                  color: Colors.greenAccent,
                  minHeight: 8,
                ),
              ),
              const SizedBox(width: 15),
              Text("${(progress * 100).toInt()}%", style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ],
          ),
        ],
      ),
    );
  }

  // 📝 ADD TASK SHEET (Simplified for brevity)
  void _showAddTaskSheet(BuildContext context) {
    final titleCtrl = TextEditingController();
    DateTime selectedDate = DateTime.now().add(const Duration(days: 1));

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (_) => Padding(
        padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom, left: 20, right: 20, top: 20),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text("New Task", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            TextField(controller: titleCtrl, decoration: const InputDecoration(hintText: "What needs to be done?")),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                if (titleCtrl.text.isEmpty) return;
                final auth = Provider.of<AuthProvider>(context, listen: false);
                final task = await Provider.of<TaskProvider>(context, listen: false).addTask(
                  eventId: widget.eventId,
                  eventName: "Event",
                  userName: auth.user?.name ?? "User",
                  taskName: titleCtrl.text,
                  deadline: selectedDate,
                );
                
                if (task != null) {
                  await NotificationService().scheduleTaskReminders(
                    task.id,
                    task.taskName,
                    task.deadline,
                  );
                }

                Navigator.pop(context);
              },
              child: const Text("Add Task"),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }
}